# docker-compose.yml (hoặc docker-compose.dev.yml)

version: '3.8'

services:
  # ========================================================
  # PostgreSQL Database Service
  # ========================================================
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      # Lưu ý: Với nhiều DB riêng biệt, các microservice sẽ kết nối đến cùng một instance PostgreSQL
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    healthcheck: # Kiểm tra sức khỏe của DB
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ========================================================
  # Redis Service
  # ========================================================
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data 
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5

  # ========================================================
  # RabbitMQ Service
  # ========================================================
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_broker
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}

    ports:
      - "${RABBITMQ_PORT:-5672}:5672" 
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s # Cho phép RabbitMQ có thời gian khởi động ban đầu

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
