# k8s/product-service/product-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service-container # Đổi tên container cho rõ ràng
        image: heisenberg8705/product-service:latest # <-- Đã thay thế bằng username của bạn
        ports:
        - containerPort: 50051 # <-- Đã điều chỉnh theo PRODUCT_SERVICE_GRPC_PORT
        env:
          # Cấu hình Database cho Product Service
          - name: DB_HOST
            value: "host.docker.internal" # <-- Đã điều chỉnh để kết nối tới DB trên máy host
          - name: DB_PORT
            value: "5432"
          - name: DB_USERNAME
            value: "postgres"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: DB_PASSWORD
          - name: PRODUCT_DB_DATABASE
            value: "product_db" # Tên database riêng cho Product Service
          - name: DB_SYNCHRONIZE
            value: "true"

          # Cấu hình gRPC Port
          - name: PRODUCT_SERVICE_GRPC_PORT
            value: "50051" # Port này cần khớp với containerPort

          # Cấu hình Redis (nếu product-service dùng Redis)
          - name: REDIS_HOST
            value: "host.docker.internal" # <-- Đã điều chỉnh để kết nối tới Redis trên máy host
          - name: REDIS_PORT
            value: "6379"

          # Cấu hình JWT (nếu product-service cần JWT_SECRET)
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: JWT_SECRET

        livenessProbe:
          tcpSocket: # <-- ĐÃ THAY ĐỔI THÀNH tcpSocket
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          tcpSocket: # <-- ĐÃ THAY ĐỔI THÀNH tcpSocket
            port: 50051
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3