# helm/cart-service/templates/servicemonitor.yaml
{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cart-service.fullname" . }}
  labels:
    {{ include "cart-service.labels" . | nindent 4 }}
    release: prometheus-stack 
spec:
  selector:
    matchLabels:
      {{ include "cart-service.selectorLabels" . | nindent 4 }}
  endpoints:
    - port: http-metrics 
      path: /metrics     
      interval: 15s      
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}