apiVersion: v1
kind: Service
metadata:
  name: {{ include "payment-service.fullname" . }}
  labels:
    {{- include "payment-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: grpc-app
    - port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.targetPort }}
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "payment-service.selectorLabels" . | nindent 4 }}
